### ISSUE TITLE
Which embeddings file exactly?

### ISSUE THREAD

**Issue by helt** [Marhabibi/TabSim#1]
Hi,

I would like to train your model. My interpretation of the paper is "word2vec with 200 dims on pubmed+pmc+wikipedia", so I would opt for http://evexdb.org/pmresources/vec-space-models/PubMed-and-PMC-w2v.bin . Is that the correct embeddings file? 

best,
Helt

**Comment by Marhabibi** [comment]
It is the correct one:

http://evexdb.org/pmresources/vec-space-models/wikipedia-pubmed-and-PMC-w2v.bin
