### ISSUE TITLE
python package requirements

### ISSUE THREAD

**Issue by helt** [Marhabibi/TabSim#2]
Im trying to get training up an running but struggle. Maybe its due to the time that has passed, the latest versions of keras, tensorflow and gensim wont get it started. However, in order to be able to reproduce your results, I would like to run your code without modifications.

Therefore I am asking, if it is possible to provide a list of requirements, e.g. a `requirements.txt`.

BR,
helt

**Comment by Marhabibi** [comment]
You can use the following versions:

keras==2.2.4
tensorflow==1.12.0
keras_self_attention==0.46.0
pandas==0.24.2
sklearn==0.19.0
numpy==1.13.3
gensim==3.2.0

**Comment by helt** [comment]
Great thanks. So python 3.6. then, correct?

**Comment by Marhabibi** [comment]
yes. The python version is 3.6.7

**Comment by helt** [comment]
## Reproducible run

```bash
git clone https://github.com/Marhabibi/TabSim.git tab-sim
cd tab-sim
wget http://evexdb.org/pmresources/vec-space-models/wikipedia-pubmed-and-PMC-w2v.bin

docker run -it --rm -v $PWD:/tabsim python:3.6.7 bash
python3 -m venv tabsim-env
source tabsim-env/bin/activate
cd tabsim
pip install -r requirements.txt
python3 TabSimTrain.py -e 1 -l 0.05 -v wikipedia-pubmed-and-PMC-w2v.bin -i tables.pickle -o test1
python3 TabSimEval.py -m test1/model-01-0.1345-0.8238-10.1599-0.8465.hdf5 -i tables.pickle -o test1

```

**Comment by helt** [comment]
maybe you want to include this into the readme?
